### ISSUE TITLE
Mutiple submit buttons in forms

### ISSUE THREAD

**Issue by alastairdb** [jmcarp/robobrowser#22]
If I have the following HTML:

```
<form name="input" action="demo_form_action.asp" method="get">
Username: <input type="text" name="user">
<input type="submit" value="Action1" name="action1_name">
<input type="submit" value="Action2" name="action2_name">
</form> 
```

When I click the Action1 button in my browser (Firefox or Chrome), the following URL gets sent `http://localhost:8001/demo_form_action.asp?user=asfdasd&action1_name=Action1`. And a different URL gets sent for Action2: `http://localhost:8001/demo_form_action.asp?user=asfdasd&action2_name=Action2`. Using the `submit_form` method in robobrowser, puts the actions for both buttons in the request:  `http://localhost:8001/demo_form_action.asp?user=asdsafd&action2_name=Action2&action1_name=Action1`.

I guess I can model the browser button pressing behaviour by deleting the buttons I do not want pressed from the robobrowser form object. However, it would be nice if the API for submit_form could be extended to include the button being pressed to submit the form.

**Comment by Lucasmrx** [comment]
Hello, can someone tell me why this giving it?

`>>> br.submit_form(form, form.fields['view_post'])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\lmr21\AppData\Local\Programs\Python\Python35\lib\site-packages\robobrowser\browser.py", line 339, in submit_form
    payload = form.serialize(submit=submit)
  File "C:\Users\lmr21\AppData\Local\Programs\Python\Python35\lib\site-packages\robobrowser\forms\form.py", line 227, in serialize
    return Payload.from_fields(include_fields)
  File "C:\Users\lmr21\AppData\Local\Programs\Python\Python35\lib\site-packages\robobrowser\forms\form.py", line 118, in from_fields
    if not field.disabled:
AttributeError: 'str' object has no attribute 'disabled'`


I have 2 Submits

**Comment by yuniesky1986** [comment]
Hello, I tell that I am using my Odoo robobrowse to connect with an external platform approving products that can be sold on the market. This platform has a form with a button that lets you fill a table with the products to be registered and after filling submit other data is a general button. In sistesis, the problem is given with the button that fills the table, because this is the format:
<Input alt = "addProduct" type = "submit" accesskey = "r" onclick = "javascript: document.forms [0] .action = '/ ..... = addProduct'" value = "Add Product" />

When I do:
browser = RoboBrowser (history = True)
browser.open ( 'https: //....../')
form = browser.get_form (action = '/ ....')
The form object contains all fields including the field where I enter the product name, but the application form:
browser.submit_form (form)
all form fields unless the product, which only applies when I click the Add Product button is recorded ..
The submit_fields property of the form is an empty list, so I can not use the option:
browser.submit_form (form, submit = submit) ..
Any proposal???
