### ISSUE TITLE
RoboBrowser and forms: .submit_form() fails when action="javascript:void(0)"

### ISSUE THREAD

**Issue by yrammos** [jmcarp/robobrowser#26]
Setting `action="javascript:void(0)"` is admittedly a rather lousy strategy for staying on the same page after clicking on the submit button, but this is what the page I'm trying to scrape does, and robobrowser unfortunately fails:
```
>>> browser.submit_form(form)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/robobrowser/browser.py", line 347, in submit_form
    response = self.session.request(method, url, **send_args)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 608, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'javascript:void(0)'
```
Thanks.

**Comment by jmcarp** [comment]
It looks like the form you're trying to submit uses javascript. Robobrowser doesn't evaluate javascript, so making this work will require a little extra work. It looks like submitting the form is supposed to send an ajax request to http://russianlearn.com/setvar.php. To make that work, you might try something like this:

```python
form.action = 'http://russianlearn.com/setvar.php'
browser.submit_form(form)
```

Or, since the ajax request returns data and not HTML, you might want to use the browser's `session` to make the request:

```python
resp = browser.session.get('http://russianlearn.com/setvar.php', params={'value': 'cat'})
```

I'm going to close the issue, since working with javascript is beyond the scope of this library, but feel free to follow up if the suggestions above don't work for you. Thanks for reporting, and sorry for the very slow response!
